### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/commission#103]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] hr_commission
- [x] sale_commission - By @hurrinico - #117 
- [x] sale_commission_formula - By @hurrinico - #122 
- [x] ~~sale_stock_commission~~ - Not needed anymore

**Comment by maxpasquinucci** [comment]
Hi pedro, can you tell if this module will be migrate to ver 10 ? 
i m a newbie in odoo so i cannot understand if i can help, actually i tried but without any success.

**Comment by pedrobaeza** [comment]
For now there are no news of any migration effort, but this is a voluntary job, so it's not planned and maybe tomorrow someone migrates them. For helping in the migration, you need to know programming and usually a lot of Odoo stuff, so it's a bit out of the scope here to say yo what to do for migrating a module.

**Comment by pedrobaeza** [comment]
Closing as main modules have been migrated. Mini module `hr_commission` can be migrated for anyone wanting it.
