### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/commission#132]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] hr_commission - By @pedrobaeza - #174 
- [x] sale_commission - By @etobella - #135 
- [x] sale_commission_formula - By @etobella - #136 
- [x] sale_commission_pricelist - @eLBati - #163

**Comment by emagdalenaC2i** [comment]
@pedrobaeza #136 is merged, should you check it here?

**Comment by pedrobaeza** [comment]
Yes, marked. I have a bit of delay checking latest merges due to the Madrid CS

**Comment by pedrobaeza** [comment]
Finished!
