### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/commission#32]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] hr_commission - By @cubells - #130 
- [x] sale_commission - By @oihane - #67
- [x] ~~sale_stock_commission~~ - Not needed anymore
- [ ] sale_commission_formula
- [ ] sale_commission_product
- [x] contract_commission - By @cubells - #119

**Comment by GMo888** [comment]
Hello,   the module is already compatible with Odoo 9 ?

**Comment by pedrobaeza** [comment]
Check the corresponding PR.

**Comment by pedrobaeza** [comment]
Closing as there's no intention of migrating the rest of the modules to this old version.
