### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/commission#373]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
- [x] account_commission - By @hildickethan-S73 - #395
- [x] commission - By @hildickethan-S73 - #394
- [x] commission_formula - By @arleite - #448
- [x] hr_commission - By @omar7r - #432
- [x] sale_commission - By @hildickethan-S73 - #396
- [x] sale_commission_agent_restrict - By @SirAionTech - #517
- [ ] sale_commission_partial_settlement - By @dalonsofl - #561
- [ ] sale_commission_pricelist - By @arleite - #425
- [ ] sale_commission_product - By @odooNextev - #546
- [x] sale_commission_product_criteria_discount - By @SirAionTech - #466
- [x] sale_commission_product_criteria_domain - By @SirAionTech - #467
- [x] sale_commission_salesman - By @omar7r - #433

**Comment by hildickethan** [comment]
Migrating `commission`, `account_commission` and `sale_commission`
- https://github.com/OCA/commission/pull/394
- https://github.com/OCA/commission/pull/395
- https://github.com/OCA/commission/pull/396

**Comment by dalonsofl** [comment]
Migrating `sale_commission_partial_settlement`

- https://github.com/OCA/commission/pull/561
